source("renv/activate.R")

# Resolve conflicts
library(conflicted)
conflict_prefer("col_factor", "readr", quiet = TRUE)
conflict_prefer("col_factor", "readr", quiet = TRUE)
conflict_prefer("collapse", "dplyr", quiet = TRUE)
conflict_prefer("discard", "purrr", quiet = TRUE)
conflict_prefer("expand", "tidyr", quiet = TRUE)
conflict_prefer("extract", "magrittr", quiet = TRUE)
conflict_prefer("filter", "dplyr", quiet = TRUE)
conflict_prefer("gather", "tidyr", quiet = TRUE)
conflict_prefer("ggsave", "ggplot2", quiet = TRUE)
conflict_prefer("here", "here", quiet = TRUE)
conflict_prefer("intersect", "dplyr", quiet = TRUE)
conflict_prefer("lag", "dplyr", quiet = TRUE)
conflict_prefer("Position", "ggplot2", quiet = TRUE)
conflict_prefer("setdiff", "dplyr", quiet = TRUE)
conflict_prefer("union", "dplyr", quiet = TRUE)
