# Load the packages this workflow depends on

library(assertr)
library(assertthat)
library(broom)
library(conflicted)
library(cowplot)
library(drake)
library(ggridges)
library(glue)
library(gt)
library(here)
library(jntools)
library(lubridate)
library(magrittr)
library(patchwork)
library(readxl)
library(scales)
library(tidyverse)
# library(ggridges)

# Resolve conflicts
col_factor <- conflict_prefer("col_factor", "readr")
collapse   <- conflict_prefer("collapse", "dplyr")
discard    <- conflict_prefer("discard", "purrr")
expand     <- conflict_prefer("expand", "tidyr")
extract    <- conflict_prefer("extract", "magrittr")
filter     <- conflict_prefer("filter", "dplyr")
gather     <- conflict_prefer("gather", "tidyr")
ggsave     <- conflict_prefer("ggsave", "ggplot2")
here       <- conflict_prefer("here", "here")
intersect  <- conflict_prefer("intersect", "dplyr")
lag        <- conflict_prefer("lag", "dplyr")
Position   <- conflict_prefer("Position", "ggplot2")
setdiff    <- conflict_prefer("setdiff", "dplyr")
union      <- conflict_prefer("union", "dplyr")
